source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
project './GitHub Viewer/Github Viewer.xcodeproj'
target 'GitHub Viewer' do
    pod 'Alamofire', '~> 4.5'
	pod 'SwiftyJSON'
end
