source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
project './GitHub Viewer/Github Viewer.xcodeproj'
target 'GitHub Viewer' do
    pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift.git', :branch => 'swift3'
    pod 'APIManager'
end
target 'GitHub ViewerTests' do
    pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift.git', :branch => 'swift3'
    pod 'APIManager'
end
